spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
#
#  thymeleaf:
#    prefix: /resources/templates/
#    suffix: .html

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #??? ??
        highlight_sql: true # SQL ??? ANSI escape codes? ???? ?? ?????.
        use_sql_comments: true
# ???????? ?? ??? ?? ???? in-memory? ???? ???? ??.
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  #?? ??? ????? ??? ?? ????? ??? ???.

