spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  #
  #  thymeleaf:
  #    prefix: /resources/templates/
  #    suffix: .html

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        highlight_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    root: info
#    운영 서버는 info
#    개발 서버는 debug
